# -*- coding: utf-8 -*-
"""analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kRCY-ujm5fk7fAi6aoVc6XkOREnzXXQC

# **Setup** & **Install**
"""

!pip install pandas matplotlib

import pandas as pd
import matplotlib.pyplot as plt

"""**#Show** **plots** **inline**"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

"""# **Upload** **CSV**"""

from google.colab import files
uploaded = files.upload()  # Select sales_data.csv
df_raw = pd.read_csv("sales_data.csv")
df_raw.head()

"""# **Clean** and **preprocess**

**#Convert** **Date** to **datetime**
"""

df = df_raw.copy()
df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

"""**#Ensure** numeric types"""

for col in ["Quantity", "Price", "Total_Sales"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

"""**#Drop** invalid rows"""

df = df.dropna(subset=["Date", "Quantity", "Price", "Total_Sales"])

"""**#Recalculate** Total_Sales and add Month"""

df["Total_Sales"] = df["Quantity"] * df["Price"]
df["Month"] = df["Date"].dt.to_period("M").astype(str)
df.head()

"""# **Basic** **analysis**"""

sales_by_product = (
    df.groupby("Product")["Total_Sales"]
      .sum()
      .sort_values(ascending=False)
)

sales_by_region = (
    df.groupby("Region")["Total_Sales"]
      .sum()
      .sort_values(ascending=False)
)

monthly_sales = (
    df.groupby("Month")["Total_Sales"]
      .sum()
      .sort_values()
)

print("Sales by product:\n", sales_by_product, "\n")
print("Sales by region:\n", sales_by_region, "\n")
print("Monthly sales:\n", monthly_sales)

"""# **Bar chart: sales by product**"""

plt.figure(figsize=(8, 5))
sales_by_product.plot(kind="bar", color="skyblue")
plt.title("Total Sales by Product")
plt.xlabel("Product")
plt.ylabel("Total Sales")
plt.tight_layout()
plt.show()

"""# **Line chart: monthly sales**"""

plt.figure(figsize=(8, 5))
monthly_sales.plot(kind="line", marker="o", color="orange")
plt.title("Total Monthly Sales")
plt.xlabel("Month")
plt.ylabel("Total Sales")
plt.grid(True, linestyle="--", alpha=0.5)
plt.tight_layout()
plt.show()

"""# **Pie chart: sales by region**

"""

plt.figure(figsize=(6, 6))
sales_by_region.plot(
    kind="pie",
    autopct="%1.1f%%",
    startangle=90,
    counterclock=False
)
plt.title("Sales Share by Region")
plt.ylabel("")
plt.tight_layout()
plt.show()